#! /bin/bash

./clean.sh
export CRAY_ACC_DEBUG=1
module load cudatoolkit

##echo "compile with pgi"
module swap PrgEnv-cray PrgEnv-pgi
make clean
make pgi-openacc

echo "Compile with cray"
#module load cudatoolkit
#make clean
module swap PrgEnv-pgi PrgEnv-cray
module load craype-accel-nvidia35
make cray-openacc 


